name: Build - Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 'Checkout Source'
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build and Validate
        run: |
          npm install
          npm run clean
          npm run build
          npm run validate
